# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
before:
  hooks:
    - rm -rf 3rdpartylicenses
    - go run github.com/google/go-licenses@latest save ./cmd/access-log-exporter --save_path=3rdpartylicenses

builds:
  - id: "access-log-exporter"
    main: ./cmd/access-log-exporter
    binary: access-log-exporter
    goos:
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Commit}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildDate={{.Date}}

archives:
  - id: access-log-exporter
    ids:
      - access-log-exporter
    formats: ['tar.xz']
    files:
      - LICENSE.txt
      - 3rdpartylicenses/**/*

nfpms:
  - id: access-log-exporter
    ids:
      - access-log-exporter
    homepage: https://github.com/jkroepke/access-log-exporter
    maintainer: Jan-Otto Kröpke <github@jkroepke.de>
    section: net
    description: |
      access-log-exporter is a management client for OpenVPN that handles the authentication of connecting users against OIDC providers like Azure AD or Keycloak.
    license: MIT License
    formats:
      - deb
      - rpm
    provides:
      - access-log-exporter
    recommends:
      - openvpn
    contents:
      - src: packaging/usr/lib/sysusers.d/
        dst: /usr/lib/sysusers.d/
      - src: packaging/usr/lib/systemd/system/
        dst: /usr/lib/systemd/system/
      - dst: /etc/access-log-exporter/
        type: dir
        file_info:
          owner: root
          group: access-log-exporter
          mode: 0750
      - dst: /etc/access-log-exporter/client-config/
        type: dir
        file_info:
          owner: root
          group: access-log-exporter
          mode: 0750
      - src: packaging/etc/access-log-exporter/config.yaml
        dst: /etc/access-log-exporter/config.yaml
        type: "config|noreplace"
        file_info:
          owner: root
          group: access-log-exporter
          mode: 0640
      - src: 3rdpartylicenses/
        dst: /usr/share/doc/access-log-exporter/3rdpartylicenses/
        type: tree
        file_info:
          owner: root
          group: root
          mode: 0644
    scripts:
      preinstall: "packaging/scripts/preinst.sh"
      postinstall: "packaging/scripts/postinst.sh"
      preremove: "packaging/scripts/preremove.sh"
      postremove: "packaging/scripts/postremove.sh"
    rpm:
      compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      #compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"

dockers:
  - goos: linux
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - 'ghcr.io/jkroepke/access-log-exporter:{{ .Version }}-amd64'
      - '{{ if and .Tag (not .Prerelease) }}ghcr.io/jkroepke/access-log-exporter:latest-amd64{{end}}'
      - '{{ if eq .Branch "main" }}ghcr.io/jkroepke/access-log-exporter:main-amd64{{end}}'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--label=org.opencontainers.image.authors=Jan-Otto Kröpke https://github.com/jkroepke/'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.description=A Prometheus exporter that receives access logs through the syslog protocol and converts them into metrics.'
      - '--label=org.opencontainers.image.documentation=https://github.com/jkroepke/access-log-exporter/wiki'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.source=https://github.com/jkroepke/access-log-exporter'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.vendor=Jan-Otto Kröpke'
      - '--label=org.opencontainers.image.version={{.Version}}'
    extra_files:
      - packaging/etc/access-log-exporter/config.yaml
  - goos: linux
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - 'ghcr.io/jkroepke/access-log-exporter:{{ .Version }}-arm64v8'
      - '{{ if and .Tag (not .Prerelease) }}ghcr.io/jkroepke/access-log-exporter:latest-arm64v8{{end}}'
      - '{{ if eq .Branch "main" }}ghcr.io/jkroepke/access-log-exporter:main-arm64v8{{end}}'
    build_flag_templates:
      - '--platform=linux/arm64/v8'
      - '--label=org.opencontainers.image.authors=Jan-Otto Kröpke https://github.com/jkroepke/'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.description=A Prometheus exporter that receives access logs through the syslog protocol and converts them into metrics.'
      - '--label=org.opencontainers.image.documentation=https://github.com/jkroepke/access-log-exporter/wiki'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.source=https://github.com/jkroepke/access-log-exporter'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.vendor=Jan-Otto Kröpke'
      - '--label=org.opencontainers.image.version={{.Version}}'
    extra_files:
      - packaging/etc/access-log-exporter/config.yaml

docker_manifests:
  - id: version
    name_template: "ghcr.io/jkroepke/access-log-exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/jkroepke/access-log-exporter:{{ .Version }}-amd64"
      - "ghcr.io/jkroepke/access-log-exporter:{{ .Version }}-arm64v8"
  - id: latest
    name_template: "{{ if and .Tag (not .Prerelease) }}ghcr.io/jkroepke/access-log-exporter:latest{{end}}"
    image_templates:
      - "{{ if and .Tag (not .Prerelease) }}ghcr.io/jkroepke/access-log-exporter:latest-amd64{{end}}"
      - "{{ if and .Tag (not .Prerelease) }}ghcr.io/jkroepke/access-log-exporter:latest-arm64v8{{end}}"
  - id: main
    name_template: '{{ if eq .Branch "main" }}ghcr.io/jkroepke/access-log-exporter:main{{end}}'
    image_templates:
      - '{{ if eq .Branch "main" }}ghcr.io/jkroepke/access-log-exporter:main-amd64{{end}}'
      - '{{ if eq .Branch "main" }}ghcr.io/jkroepke/access-log-exporter:main-arm64v8{{end}}'

docker_signs:
  - artifacts: manifests
    output: true
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign
      - '--oidc-issuer={{if index .Env "CI"}}https://token.actions.githubusercontent.com{{else}}https://oauth2.sigstore.dev/auth{{end}}'
      - '--yes'
      - '${artifact}'

checksum:
  name_template: "checksums.txt"

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

release:
  prerelease: auto

changelog:
  use: github-native

sboms:
  - artifacts: archive
