global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'access-log-exporter'
    static_configs:
      - targets: ['access-log-exporter:4040']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
